services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    post_start:
      - command: python manage.py migrate

  server_manage:
    build: .
    container_name: server_manage
    entrypoint: python manage.py

  server_tests:
    build: .
    container_name: server_tests
    env_file:
      - .env.test
    depends_on:
      - db
    entrypoint: pytest

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - itworld-storage:/var/lib/postgesql

volumes:
  itworld-storage: