# Generated by Django 6.1 on 2026-08-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('api_key', models.CharField(unique=True)),
                ('webhook_url', models.CharField()),
                ('webhook_secret', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('UNDERPAID', 'Underpaid'), ('OVERPAID', 'Overpaid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.project')),
                ('idempotency_key', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expired_at'], name='invoice_status_expired_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'idempotency_key'), name='invoice_project_idempotency_key_key')],
            }
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(unique=True)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('type', models.CharField(choices=[('FUND', 'Fund'), ('FEE', 'Fee')])),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.merchant')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='payments.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'dt'], name='ledger_merchant_dt_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_payment_amount_positive_check')],
            },
        ),
    ]
