# Generated by Django 6.1 on 2026-08-27 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
