# Generated by Django 6.1 on 2026-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_project_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='idempotency_key',
            field=models.UUIDField(),
        ),
    ]
