# Generated by Django 6.1 on 2026-08-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='currency',
        ),
        migrations.AddField(
            model_name='ledger',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='payments.invoice'),
        ),
    ]
