# Generated by Django 6.1 on 2026-08-30 11:47

from django.db.models import OuterRef, Subquery, Value
import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Coalesce


def forwards_func(apps, schema_editor):
    Invoice = apps.get_model("payments", "Invoice")
    Ledger = apps.get_model("payments", "Ledger")
    db_alias = schema_editor.connection.alias

    Ledger.objects.using(db_alias).update(
        project=Coalesce(Subquery(Invoice.objects.filter(pk=OuterRef('invoice')).values('project')[:1]), Value(1))
    )


def reverse_func(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_ledger_currency_ledger_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='payments.project'),
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
        migrations.AlterField(
            model_name='ledger',
            name='project',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.RESTRICT, to='payments.project'),
        )
    ]
