# Generated by Django 6.1 on 2026-08-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_ledger_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
