# Generated by Django 6.1 on 2026-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=24),
        ),
    ]
