# Generated by Django 6.1 on 2026-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_exchangerate_rate_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledger',
            name='ledger_merchant_dt_idx',
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['invoice_id', 'type'], include=('amount',), name='ledger_invoice_id_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency'), include=('rate',), name='exchangerate_base_target_currency_key'),
        ),
    ]
